development:
  adapter: postgresql
  encoding: unicode
  database: Rooster_development
  host: localhost
  pool: 5
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: Rooster_test
  host: localhost
  pool: 5
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>


production:
  adapter: postgresql
  encoding: unicode
  database: Rooster_production
  host: localhost
  pool: 5
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

